### ISSUE TITLE
[all] JSON validation

### ISSUE THREAD

**Issue by rhlsthrm** [connext/indra#1001]
Found this library: https://github.com/ostrowr/ts-json-validator

The idea is it does validation of JSON objects when parsing it after it comes over the wire. This is important to do in a couple of places:

- [ ] Upon handling a received message from cf-core protocol.
- [ ] Upon node receiving a NATS message from the client.

Not a drop everything task, but will definitely raise our velocity.

**Comment by ArjunBhuptani** [comment]
We'll be working towards custom JSON objects as part of performance optimization, closing
