### ISSUE TITLE
[client, node] Correctly prefix all messages with senderIdentifier.nodeIdentifier

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1079]
This work was started in https://github.com/connext/indra/pull/1072 but needs to be pushed over the finish line.

Also TODO we need to have a chat about how this scales to multihop. Perhaps it should be `senderIdentifier.receiverIdentifier`?

**Comment by rhlsthrm** [comment]
I think it should be `receiverIdentifier.senderIdentifier`. This way, receivers can subscribe to all messages meant for them easily with `subscribe("MY_IDENTIFIER.>")`.

**Comment by ArjunBhuptani** [comment]
yeah that works^
