### ISSUE TITLE
[store] Deferred promises dedupe

### ISSUE THREAD

**Issue by LayneHaber** [connext/indra#1154]
**Describe the bug**
When adding deferred promises to the array in the `execute` function of the store, each promise is added to the end of the array, and all of the instructions are executed.

When many promises are thrown at the store simultaneously, like in [this](https://github.com/connext/indra/blob/42f56ce49e0a1c561cb649932b882a41b271a86f/modules/store/src/methods.spec.ts#L418) test, this will result in multiple duplicate calls to the store because the deferred promises could be executed multiple times. This contributes to high latency of store calls in this payment. Ideally deferred instructions should be intelligently executed.

**Comment by ArjunBhuptani** [comment]
Will be fixed by switching to sequelize-based stores, closing
