### ISSUE TITLE
External direct deposits v1

### ISSUE THREAD

**Issue by kilrau** [connext/indra#1172]
**Is your feature request related to a problem? Please describe.**
As discussed, we would want to have predecessor of https://github.com/connext/indra/issues/1166 to enable external direct deposits from a UX perspective (even though under the hood there are still 2 steps and 2 on-chain transactions).

**Describe the solution you'd like**
1. connext client returns 0x address
2. user deposits to 0x address
3. connext client sends meta transaction to node
4. node executes this second transaction on user's behalf

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ArjunBhuptani** [comment]
Will work on setting this up this week

**Comment by kilrau** [comment]
Dope!

**Comment by ArjunBhuptani** [comment]
Closing this -- as per our discussion a few weeks back, this is sadly not possible without requiring more upfront work from the user
