### ISSUE TITLE
Use better event emitter

### ISSUE THREAD

**Issue by rhlsthrm** [connext/indra#1176]
This one would solve a lot of problems we have been dealing with: https://github.com/garronej/evt

**Comment by garronej** [comment]
@rhlsthrm @LayneHaber Hello 👋 
I am very excited to see EVT being integrated into such a cool solution.
Would it be ok for you guys if I include Connext into a section where I mention who is using EVT?

**Comment by rhlsthrm** [comment]
Hey @garronej! We would love to be included! Please let us know if you need more info!

**Comment by garronej** [comment]
@rhlsthrm that is very cool of you.
If you feel like you could provide me a quote about why you chose to adopt EVT and how it has been working for you so far.  
It would be great publicity for EVT and it could hopefully redirect some traffic your way.

What do you think?

**Comment by rhlsthrm** [comment]
"At Connext, we are building complex, distributed systems that rely heavily on event-driven processes. We eventually found that the capabilities of the Node.js EventEmitter could not handle some of our more complex event-based needs such as attaching an event based on a filter. We are grateful to have found EVT as a suitable replacement which gives us strong typing and a powerful API for all of our eventing needs. We were able to eliminate a lot of boilerplate and complicated code around resolving promises and detaching listeners by using `waitFor`. We have also exposed the EVT interface through our API so our users can make use of these powerful features."

- Rahul Sethuram, CTO at [Connext](https://connext.network)

Let me know if this works okay @garronej. Also please let us know when this quote is up, we will promote it on our social channels as well.

Thanks again for the great package!

**Comment by garronej** [comment]
I am very flattered by what you wrote. @rhlsthrm, thank you.
I have included your quote on the home page [evt.land](https://evt.land). Is everything ok for you?

**Comment by rhlsthrm** [comment]
Yes, please do! Let us know when it's up, as I said we are happy to promote it.

**Comment by garronej** [comment]
It is up 🚀
https://evt.land
🙏🏻
