### ISSUE TITLE
[cf-core] Sync on validating sig error

### ISSUE THREAD

**Issue by rhlsthrm** [connext/indra#1250]
Catch validating sig error, re-sync, and retry protocol. We should also write tests for this.

**Comment by ArjunBhuptani** [comment]
Closing duplicate (I just opened this lolol)

**Comment by rhlsthrm** [comment]
This removes the need to prioritize the queue. We can do this the following way:
- Catch initiator protocol errors in `MethodController`.
- If initiator protocol error === sig validation error, run sync and re-run protocol.
- If responder errors, send back the message with error, initiator re-throws it, and runs the same sync + re-run process.
