### ISSUE TITLE
Conditional transfer sender did not receive CREATED event

### ISSUE THREAD

**Issue by erkarl** [connext/indra#1277]
Experienced this on mainnet with 7.0.0.alpha6:
- sender sent 0.001 ETH
- node collateralized 0.05 ETH to the receiver
- receiver got `CREATED` event
- sender never got `CREATED` event

[connext-mainnet-sender-fail.log](https://github.com/connext/indra/files/4840227/connext-mainnet-sender-fail.log)
[connext-mainnet-fail-receiver.log](https://github.com/connext/indra/files/4840229/connext-mainnet-fail-receiver.log)
[connext-mainnet-node.log](https://github.com/connext/indra/files/4840231/connext-mainnet-node.log)

**Comment by ArjunBhuptani** [comment]
Closing because we haven't been able to repro or get any more data on this. We can reopen if it pops up again with more info.
