### ISSUE TITLE
[all] SQLite -- SequelizeTimeoutError: SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1297]
**Describe the bug**
During tps tests, SQLite sometimes throws the following:
```
SequelizeTimeoutError: SQLITE_BUSY: database is locked
```

It looks like this is called by deadlocking during concurrent reads/writes which SQLite doesn't handle very well by default. See: https://github.com/sequelize/sequelize/issues/10304

**To Reproduce**
Run the tps tests a bunch until they error -- this will typically show up when one or many clients are syncing and erroring repeatedly.

**Comment by rhlsthrm** [comment]
#1302
