### ISSUE TITLE
Evt timeout after 60000ms

### ISSUE THREAD

**Issue by erkarl** [connext/indra#1340]
**What happened?**
Mainnet conditional transfer failed when trying to send `0.01` ETH. Node's balance decreased by `0.0625` ETH. Sender's balance **DID NOT** decrease by `0.01` ETH.

[connext_sender.log](https://github.com/connext/indra/files/4983582/connext_sender.log)
[connext_receiver.log](https://github.com/connext/indra/files/4983583/connext_receiver.log)
[node.log](https://github.com/connext/indra/files/4983585/node.log)

When checking the status of the payment via `rest-api-client` we're getting the following outputs:

Sender side:
```
bash-5.0# curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0xf4a8078ccc8f0872038e55b60840673e27a4efca4359fa82ee7419a6a0b973e8/0x0000000000000000000000000000000000000000 | jq

{
  "senderIdentifier": "indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h",
  "receiverIdentifier": "indra7CuXwXvHb8AP3gyKm4n9YuUQnmWaE7FxcNkokcbTp9WkZ4qpus",
  "assetId": "0x0000000000000000000000000000000000000000",
  "amount": "10000000000000000",
  "lockHash": "0xf4a8078ccc8f0872038e55b60840673e27a4efca4359fa82ee7419a6a0b973e8",
  "expiry": "10542856"
}
```

and on the receiver side the transfer does not exist:
```
bash-5.0# curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0xf4a8078ccc8f0872038e55b60840673e27a4efca4359fa82ee7419a6a0b973e8/0x0000000000000000000000000000000000000000 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177  100   177    0     0    333      0 --:--:-- --:--:-- --:--:--   333
{
  "message": "No HashLock Transfer found for lockHash: 0xf4a8078ccc8f0872038e55b60840673e27a4efca4359fa82ee7419a6a0b973e8 and assetId: 0x0000000000000000000000000000000000000000"
}
```

When the receiver tries to query the status of the transfer the node's logs are displaying:
```
2020-07-27T17:18:54.130Z [LinkedTransferMessaging] Cannot get hashlock transfer app for third party. Requestor pubId: indra7CuXwXvHb8AP3gyKm4n9YuUQnmWaE7FxcNkokcbTp9WkZ4qpus,
        sender pubId: indra5GYKLaTiQg6SQh8iztaAkYkZFowfbDMw8LSnZdwpv2YdjWxq5h, receiver pubId: undefined
```

Node: `* (HEAD detached at 5c378ae4d)`
Clients: `7.0.0`

**Comment by erkarl** [comment]
Also note that the sender's `client.getHashLockTransfer(lockHash, assetId)` is missing `status` field.

```
declare type GetHashLockTransferResponse = {
    senderIdentifier: PublicIdentifier;
    receiverIdentifier?: PublicIdentifier;
    assetId: Address;
    amount: DecString;
    lockHash: Bytes32;
    status: HashLockTransferStatus;
    meta?: any;
    preImage: Bytes32;
    expiry: BigNumber;
} | undefined;
```

shouldn't it be one of these?
```
export declare const TransferWithExpiryStatuses: {
    readonly EXPIRED: "EXPIRED";
    readonly PENDING: "PENDING";
    readonly COMPLETED: "COMPLETED";
    readonly FAILED: "FAILED";
};
```

**Comment by LayneHaber** [comment]
Yes -- it should have a `PENDING` field, but it's likely it's returned undefined if it cannot find the receiver app. Will double check the logic here.

**Comment by kilrau** [comment]
So this happens 100% of the time for us now, on different networks with channels containing enough collateral. Restarting the node/wiping clients didn't help.
