### ISSUE TITLE
[All] Post-spacefold cleanup

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1354]
There were a lot of hotfixes/changes specifically pushed into the spacefold branch as part of the demo. We should work on cleaning these up, properly testing them, and then merging them to staging.

The spacefold branch itself probably doesn't need to be merged.

**Comment by rhlsthrm** [comment]
If we provide a way for the sender client to specify RequireOnline for the Linked Transfer app, we don't actually need spacefold on a separate branch. IMO this would be the best way to do it rather than maintaining a separate fork/

**Comment by bohendo** [comment]
I asked:

>  Can someone explain the move of SimpleLinkedTransferApp from AllowOfflineAppNames to RequireOnlineAppNames?

@ArjunBhuptani answered:

> The rationale specifically for spacefold was that otherwise it's possible for the collateralization on the second chain to fail and then money looks like it disappeared (even though it's just being held until the next reconnect)
> However it definitely shouldn't be in both categories. That will not work
> We should just have a SimpleOnlineTransfer that extends SimpleLinkedTransfer

**Comment by bohendo** [comment]
So far, I've added an extra app name. Our simple linked transfer app now goes by two names: `OnlineLinkedTransferApp` and `SimpleLinkedTransferApp`. This lets us treat one as online-only and the other as allow-offline while still sharing all the same core app logic.

One hiccup is that we need to add some special cases while retrieving the app definition address. A minor inconvenience but still tricky & bug-prone..

```
        // Special case: OnlineLinkedTransferApp uses same contract as SimpleLinkedTransferApp
        const appDefinitionAddress = contractAddresses[
          app.name === SupportedApplicationNames.OnlineLinkedTransferApp
            ? SupportedApplicationNames.SimpleLinkedTransferApp
            : app.name
        ];
```

**Comment by bohendo** [comment]
So here's a monkey wrench re two apps with different names & same info otherwise:
```
  public getAppInfoByAppDefinitionAddress(appDefinition: string): DefaultApp {
    return this.appRegistryMap.get(appDefinition);
  }
```
In several places the node retrieves the app info from it's definition address.. this won't work w my current strategy & I'm not 100% sure how to proceed..

**Comment by rhlsthrm** [comment]
What we are going to have to do is create a new app contract which inherits/extends the old one. I think you can do something like:

```
contract OnlineLinkedTransferApp is SimpleLinkedTransferApp {}
```

Then you would have to make all the types and everything, but going through that exercise would help optimize it. Every time someone builds a new app they make more optimizations around the process and it gets easier and easier (it's still hard however).

**Comment by bohendo** [comment]
I don't really like the idea of creating a separate yet identical contract just to deal w this one little flag. Why not add a `requireOnline` boolean flag to the app state's meta field instead?

**Comment by rhlsthrm** [comment]
> Why not add a requireOnline boolean flag to the app state's meta field instead?

My fear is that it complicates the meta with extra flags that implementers then need to understand. If we keep it at the app level, it's easier to reason about that there is an `OnlineLinkedTransfer` app vs a `SimpleLinkedTransfer` app (probably even makes sense to change this to `AsyncLinkedTransfer`.
