### ISSUE TITLE
[node, client] Return wrapped tx object for deposit/withdraw/collateral

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1359]
Currently, to properly wait on a collateralization request we have to:
```
const tx = await client.requestCollateral(AddressZero) as any;
await ethProvider.waitForTransaction(tx.hash);
await client.waitFor(EventNames.UNINSTALL_EVENT, 10_000);
```
This is kind of ugly & requires arcane knowledge of event names. This waiting process should be simpler but `requestCollateral` still needs to return asap

**Comment by bohendo** [comment]
Returning something like `{ tx: TransactionResponse; finished: Promise<void> }` might be good.

Then the end user can wait on the tx & protocol separately. We need to be careful to document this carefully though so these two things we can wait on don't get mixed up.
