### ISSUE TITLE
do not install transfer apps when client receives 60 sec timeout error

### ISSUE THREAD

**Issue by erkarl** [connext/indra#1379]
mainnet:
1. sender's transfer from rest-api-client got 60 sec evt timeout because the collateralization tx took forever to confirm
2. several minutes later the tx was confirmed and the node installed the sender/receiver app
3. from xud side the swap had already been timed out and it doesn't attempt to unlock
4. ERROR: sender's funds are now locked for ~6900 blocks

Desired behaviour:
The node should cancel the operation and not fully install the sender app if the timeout occurs

**Comment by erkarl** [comment]
Just to clarify this happened with ETH transfer.

**Comment by LayneHaber** [comment]
The node is not aware of the timeout, it's artificially put in place so that the client calls don't hang indefinitely. We could include the same timer on the node side, but I'm not sure that's truly the desired behavior.

What do you mean by:
> from xud side the swap had already been timed out and it doesn't attempt to unlock
