### ISSUE TITLE
USDT transfers and withdrawals don't work

### ISSUE THREAD

**Issue by erkarl** [connext/indra#1380]
From @LayneHaber 

> The transfer function copied above does not have a return value, so, strictly speaking, the contract doesn't conform to the ERC20 spec

**Comment by LayneHaber** [comment]
[Transfer helper](https://github.com/Uniswap/uniswap-lib/blob/master/contracts/libraries/TransferHelper.sol) from Uniswap

**Comment by rhlsthrm** [comment]
Not actually fixed, transfer collateralizations still failing.
