### ISSUE TITLE
Pre-Collateralization

### ISSUE THREAD

**Issue by kilrau** [connext/indra#1405]
**Is your feature request related to a problem? Please describe.**
Mainnet usage has shown, that "on-the-fly" collateralization is not a great long-term approach since it relies on getting a transaction into the next block. Not only is accurate gas estimation for the next block difficult, but also very expensive. In practice we are experiencing confirmation times of several minutes and timeouts as a result. Further, we'd need to be able to set the desired amount for the collateralization since the current default of e.g. 20 USDT triggers a live collateralization (and hence a swap timeout) for all trades of greater 20 USDT

**Describe the solution you'd like**
We think pre-collateralizing a channel with an estimated amount is the better way. Since the indra node doesn't know anything about trades/estimated amounts as of now, we think it makes sense for the client to provide this information and pass it in the collateralization request.

- add amount field collateralization call `(  export type PostRequestCollateralRequestParams = MultiClientRequestParams & { assetId: string };`), this allows xud to request collateral for the required amount via the client before/when an order is entering the order book based on the order amount
- to avoid draining node funds, we would need to be able to set a fixed upper limit per currency per client for the collateralization in the node
- the client would need to get notified with the collateralization tx hash from the node the same way currently deposits do, collateralization status or simply the remote balance needs to be exposed via the rest-api

**Comment by ArjunBhuptani** [comment]
Updating based on our discussion:

Request collateral and collateralization profiles already largely cover the needs here. All we need to do is:
1. Expose collateral profile setup via config
2. Allow passing in an `amount` to `requestCollateral`. If an `amount` is passed in, collateralize up to `amount` so long as `currBal + amount <= upperBound`
