### ISSUE TITLE
Insufficient funds error should be handled more gracefully

### ISSUE THREAD

**Issue by bohendo** [connext/indra#268]
**Describe the bug**
Currently, when the hub runs out of money, it spews out a bunch of errors and stack traces including:
```
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to create channel. Multisignature wallet cannot be deployed properly: {
```
**This promise rejection shouldn't be unhandled.** We should catch it and do what's needed to handle this case cleanly.

It also retries three times which, in the case of having an insufficient balance, doesn't really make sense.

**To Reproduce**
Watch hub logs while it has a low balance while someone tries to make a channel 

**Expected behavior**
Log the error and maybe pass an informative message to it's clients that the hub can't deploy channels until it gets more money

**Comment by ArjunBhuptani** [comment]
Loop in with #331

**Comment by ArjunBhuptani** [comment]
There's been several instances where this has occurred in the past week. 

Prior to attempting to: 
(a) deploy state deposit holder,
(b) collateralize a channel (in Eth or tokens),
(c) submit a transaction onchain;
the node should check to see if it has sufficient balance in it's own signer address. If not, it should throw a more verbose error.
