### ISSUE TITLE
[client] Refactor async payments to use NATS streaming

### ISSUE THREAD

**Issue by rhlsthrm** [connext/indra#397]
Use durable subscriptions to retrieve on startup rather than querying node.

**Comment by rhlsthrm** [comment]
Necessary for decentralization, but not to make things work.

**Comment by hthillman** [comment]
@rhlsthrm can this be closed or is it still pending @kthomas's NATS work?

**Comment by rhlsthrm** [comment]
Still pending NATS work. We punted this until after Daicard goes live.

**Comment by ArjunBhuptani** [comment]
Stale (and the explicit checkin seems to be a better idea for now)
