### ISSUE TITLE
[cf-core] Symmetric event emission

### ISSUE THREAD

**Issue by LayneHaber** [connext/indra#627]
**Describe the bug**
Only the responder in a protocol receives an event once the protocol is finished, the initiator does not. This is annoying, and we should refactor so both parties receive events when protocols are finished.

**Comment by LayneHaber** [comment]
Update: desirable, but blocked by channel provider not receiving remote events. Blocked by #730

**Comment by ArjunBhuptani** [comment]
Closing this because it's effectively done minus the work needed in #730
