### ISSUE TITLE
[cf-core] Race condition collateralizing/withdrawing

### ISSUE THREAD

**Issue by LayneHaber** [connext/indra#705]
[This](https://github.com/ConnextProject/indra/blob/bba37b3bf7fca83b1bf6080d3e8d235010c2c2b4/modules/test-runner/src/withdraw/withdraw.test.ts#L82) test should pass, and it fails intermittently with validating signature errors

**Comment by ArjunBhuptani** [comment]
Note: this *should* be fixed by the new withdraw + deposit when those are completed

**Comment by ArjunBhuptani** [comment]
Works now
