### ISSUE TITLE
[client, cf-core] Should we throw errors when getting broken channels?

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#710]
Calling getStateChannel for the following cases:
1) State channel under multisig key has no proxy factory address
2) State channel under multisig key has no freeBalanceAppInstance
3) Store contains state channel on wrong multisig address
...always resolves but with incorrect info.

Should we build validators to check channel data is present/accurate and throw errors if it isn't? Or should this just be a flat getter and we handle that elsewhere?

**Comment by LayneHaber** [comment]
I think it would be a good idea to build validators to make sure its at least in the right structure.

This would have helped us limit the damage done by the `proxyAddress` bugs we saw earlier

**Comment by LayneHaber** [comment]
At the very least we could leave it as a pure getter and verify it has the correct structure on `connect`

**Comment by ArjunBhuptani** [comment]
Doing it on `connect` seems like a good idea since we already have a flow to restore if the channel is missing from store
