### ISSUE TITLE
QueryFailedError: deadlock detected

### ISSUE THREAD

**Issue by bohendo** [connext/indra#966]
**Describe the bug**
`QueryFailedError: deadlock detected` probably bc we're trying to modify two postgres tables at the same time. 

**To Reproduce**

revert fix in commit `58f016521` then run integration tests.

**Expected behavior**

no errors

**Comment by ArjunBhuptani** [comment]
Stale, closing (we can reopen if we see this issue again but it hasn't popped up in a long while)
