### ISSUE TITLE
[contracts] address solc compiler warnings

### ISSUE THREAD

**Issue by bohendo** [connext/indra#973]
Ideally we'd pay attention to solc compiler warnings to warn us of any issues.

Contracts are much harder to upgrade than other parts of our code, it'll be less risky for us if we notice & address issues as early as possible & compiler warnings are a big help w that.

Currently, there are so many warnings that any meaningful signal is lost to noise.

This will require us to upgrade to solidity v0.6, if this requires too many syntax changes or risks breaking anything then we should decrease the priority of this issue.

**Comment by bohendo** [comment]
blocked by lack of solidity 0.6 support by OpenZeppelin, revist this issue once they release v3
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2086

**Comment by ArjunBhuptani** [comment]
Completed via https://github.com/connext/indra/pull/1122
